AWSTemplateFormatVersion: '2010-09-09'
Description: Enable Cognito Managed Login using AWS Default Branding

Parameters:
  UserPoolId:
    Type: String

  ClientId:
    Type: String

Resources:
  ManagedBranding:
    Type: AWS::Cognito::ManagedLoginBranding
    Properties:
      UserPoolId: !Ref UserPoolId
      ClientId: !Ref ClientId
      UseCognitoProvidedValues: true
